name: Build

on:
 pull_request:
  branches:
   - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Clone repository
     uses: actions/checkout@v2

   - uses: actions/setup-node@v3
     with:
      node-version: 19

   - name: Install dependencies
     run: npm ci

   - name: Generate build
     env:
      CI: false
     run: npm run build

   - name: Upload Build
     uses: actions/upload-artifact@v1
     with:
      name: build
      path: dist
